export { default as Home } from './Home'
export { default as Job } from './Job'
export { default as Learning } from './Learning'
export { default as Projects } from './Projects'
export { default as Sitemap } from './Sitemap'
export { default as Tasks } from './Tasks'